'use strict';
// Fonte do catálogo de tweaks de registro. Fica SÓ no servidor: `node tools/export-catalog.js` gera functions/catalog.json.
const R = (hive, path, name, type, value) => ({ hive, path, name, type, value });
const SP = 'SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Multimedia\\SystemProfile';
const GCS = 'System\\GameConfigStore';
const CV = 'Software\\Microsoft\\Windows\\CurrentVersion';
const CATALOG = [
  // ---------------- PERFORMANCE / CPU ----------------
  { id: 'cpu.prio', cat: 'Performance', title: 'Separação de prioridade (Win32PrioritySeparation)', evidence: 'community', risk: 'low', admin: true,
    desc: 'Define quantum curto/fixo com boost 3:1 para a janela em primeiro plano (0x2A). O padrão de cliente (0x02) já usa quantum curto e variável; a diferença prática costuma ser pequena e depende do jogo — meça.',
    changes: [R('HKLM', 'SYSTEM\\CurrentControlSet\\Control\\PriorityControl', 'Win32PrioritySeparation', 'REG_DWORD', 42)] },
  { id: 'cpu.mmcss', cat: 'Performance', title: 'Perfil MMCSS "Games" (prioridade de agendamento)', evidence: 'documented', risk: 'low', admin: true,
    desc: 'Parâmetros documentados do Multimedia Class Scheduler: Priority 6 e Scheduling Category High para tarefas "Games".',
    changes: [R('HKLM', SP + '\\Tasks\\Games', 'Priority', 'REG_DWORD', 6), R('HKLM', SP + '\\Tasks\\Games', 'Scheduling Category', 'REG_SZ', 'High'),
      R('HKLM', SP + '\\Tasks\\Games', 'GPU Priority', 'REG_DWORD', 8), R('HKLM', SP + '\\Tasks\\Games', 'SFIO Priority', 'REG_SZ', 'High')] },
  { id: 'cpu.sysresp', cat: 'Performance', title: 'SystemResponsiveness = 10', evidence: 'documented', risk: 'low', admin: true,
    desc: 'Percentual de CPU reservado a tarefas de baixa prioridade quando há tarefas multimídia/jogo ativas. Padrão 20.',
    changes: [R('HKLM', SP, 'SystemResponsiveness', 'REG_DWORD', 10)] },
  { id: 'cpu.throttle', cat: 'Performance', title: 'Desativar Power Throttling (EcoQoS)', evidence: 'documented', risk: 'low', admin: true,
    desc: 'Impede o Windows de limitar processos em segundo plano via EcoQoS. Mais útil em notebooks.',
    changes: [R('HKLM', 'SYSTEM\\CurrentControlSet\\Control\\Power\\PowerThrottling', 'PowerThrottlingOff', 'REG_DWORD', 1)] },
  { id: 'cpu.timerres', cat: 'Performance', title: 'Restaurar resolução global de timer (Windows 11)', evidence: 'documented', risk: 'low', admin: true, reboot: true,
    desc: 'GlobalTimerResolutionRequests=1 restaura o comportamento em que um app que pede timer de alta resolução afeta o sistema todo (Win11 e Server 2022+). Aumenta um pouco o consumo de energia.',
    changes: [R('HKLM', 'SYSTEM\\CurrentControlSet\\Control\\Session Manager\\kernel', 'GlobalTimerResolutionRequests', 'REG_DWORD', 1)] },
  { id: 'net.throttleidx', cat: 'Performance', title: 'NetworkThrottlingIndex = desativado', evidence: 'documented', risk: 'low', admin: true,
    desc: 'Remove o limite de pacotes/ms para tráfego não-multimídia enquanto há mídia tocando (padrão 10).',
    changes: [R('HKLM', SP, 'NetworkThrottlingIndex', 'REG_DWORD', 4294967295)] },
  // ---------------- GAMING / GPU ----------------
  { id: 'game.mode', cat: 'Gaming', title: 'Game Mode ativado', evidence: 'documented', risk: 'low',
    desc: 'Ativa o Game Mode do Windows (prioriza o jogo e evita instalação de drivers via Windows Update durante a sessão).',
    changes: [R('HKCU', 'Software\\Microsoft\\GameBar', 'AutoGameModeEnabled', 'REG_DWORD', 1), R('HKCU', 'Software\\Microsoft\\GameBar', 'AllowAutoGameMode', 'REG_DWORD', 1)] },
  { id: 'game.dvr', cat: 'Gaming', title: 'Desativar captura em segundo plano (Game DVR)', evidence: 'documented', risk: 'low',
    desc: 'Desliga a gravação em segundo plano da Xbox Game Bar, que consome GPU/disco.',
    changes: [R('HKCU', GCS, 'GameDVR_Enabled', 'REG_DWORD', 0), R('HKCU', CV + '\\GameDVR', 'AppCaptureEnabled', 'REG_DWORD', 0)] },
  { id: 'game.fso', cat: 'Gaming', title: 'Otimizações de tela cheia: modo exclusivo (global)', evidence: 'community', risk: 'low',
    desc: 'Faz o Windows respeitar tela cheia exclusiva em vez de "fullscreen otimizado". Alguns jogos ganham consistência, outros não — meça.',
    changes: [R('HKCU', GCS, 'GameDVR_FSEBehaviorMode', 'REG_DWORD', 2), R('HKCU', GCS, 'GameDVR_HonorUserFSEBehaviorMode', 'REG_DWORD', 1), R('HKCU', GCS, 'GameDVR_DXGIHonorFSEWindowsCompatible', 'REG_DWORD', 1)] },
  { id: 'gpu.hags', cat: 'Gaming', title: 'Agendamento de GPU acelerado por hardware (HAGS)', evidence: 'community', risk: 'medium', admin: true, reboot: true,
    desc: 'HwSchMode=2 liga o HAGS (requer GPU/driver compatíveis). Pode melhorar ou piorar conforme o jogo/driver; recomendo medir. Desfazer retorna ao valor anterior.',
    changes: [R('HKLM', 'SYSTEM\\CurrentControlSet\\Control\\GraphicsDrivers', 'HwSchMode', 'REG_DWORD', 2)] },
  { id: 'gpu.mpo', cat: 'Gaming', title: 'Desativar MPO (Multiplane Overlay)', evidence: 'workaround', risk: 'medium', admin: true, reboot: true,
    desc: 'OverlayTestMode=5 desativa o MPO no DWM. É uma correção para flicker/stutter/tela preta em alguns drivers — NÃO é um ganho geral de latência. Aplique só se tiver o sintoma.',
    changes: [R('HKLM', 'SOFTWARE\\Microsoft\\Windows\\Dwm', 'OverlayTestMode', 'REG_DWORD', 5)] },
  { id: 'gpu.tdr', cat: 'Gaming', title: 'TdrDelay = 10 s (estabilidade sob carga alta)', evidence: 'workaround', risk: 'low', admin: true, reboot: true,
    desc: 'Aumenta o tempo antes do Windows reiniciar o driver gráfico (padrão 2 s). Evita falsos timeouts em cargas pesadas; não reduz latência.',
    changes: [R('HKLM', 'SYSTEM\\CurrentControlSet\\Control\\GraphicsDrivers', 'TdrDelay', 'REG_DWORD', 10)] },
  // ---------------- KERNEL / MEMÓRIA / I/O ----------------
  { id: 'mem.nopageexec', cat: 'Performance', title: 'DisablePagingExecutive (manter kernel/drivers na RAM)', evidence: 'documented', risk: 'medium', admin: true, reboot: true,
    desc: 'Impede que o código do kernel e drivers sejam paginados para o disco. Só faz sentido com RAM de sobra (≥16 GB).',
    changes: [R('HKLM', 'SYSTEM\\CurrentControlSet\\Control\\Session Manager\\Memory Management', 'DisablePagingExecutive', 'REG_DWORD', 1)] },
  { id: 'io.ntfsmem', cat: 'Storage', title: 'NtfsMemoryUsage = 2 (cache NTFS maior)', evidence: 'documented', risk: 'low', admin: true, reboot: true,
    desc: 'Aumenta o pool paginado usado pelo NTFS (equivale a "fsutil behavior set memoryusage 2"). Ajuda com muitos arquivos pequenos; não afeta FPS diretamente.',
    changes: [R('HKLM', 'SYSTEM\\CurrentControlSet\\Control\\FileSystem', 'NtfsMemoryUsage', 'REG_DWORD', 2)] },
  { id: 'io.8dot3', cat: 'Storage', title: 'Desativar criação de nomes 8.3 no NTFS', evidence: 'documented', risk: 'medium', admin: true, reboot: true,
    desc: 'Reduz overhead em diretórios grandes. Instaladores muito antigos podem depender de nomes 8.3; por isso é marcado como risco médio.',
    changes: [R('HKLM', 'SYSTEM\\CurrentControlSet\\Control\\FileSystem', 'NtfsDisable8dot3NameCreation', 'REG_DWORD', 1)] },
  { id: 'io.lastaccess', cat: 'Storage', title: 'Desativar atualização de "último acesso" (NTFS)', evidence: 'documented', risk: 'low', admin: true, reboot: true,
    desc: 'Evita uma escrita de metadados a cada leitura de arquivo. Em Windows 10/11 o padrão já é gerenciado pelo sistema.',
    changes: [R('HKLM', 'SYSTEM\\CurrentControlSet\\Control\\FileSystem', 'NtfsDisableLastAccessUpdate', 'REG_DWORD', 0x80000001)] },
  // ---------------- INPUT ----------------
  { id: 'input.mouseaccel', cat: 'Performance', title: 'Desativar "Aprimorar precisão do ponteiro" (aceleração)', evidence: 'documented', risk: 'low', group: 'mouse',
    desc: 'Remove a aceleração do ponteiro no Windows (MouseSpeed/Threshold = 0). Não altera sua sensibilidade (mantém o controle deslizante). Aplicado imediatamente.',
    changes: [R('HKCU', 'Control Panel\\Mouse', 'MouseSpeed', 'REG_SZ', '0'), R('HKCU', 'Control Panel\\Mouse', 'MouseThreshold1', 'REG_SZ', '0'), R('HKCU', 'Control Panel\\Mouse', 'MouseThreshold2', 'REG_SZ', '0')],
    live: { kind: 'mouse', args: [0, 0, 0] }, liveUndo: { kind: 'mousePrev' } },
  { id: 'input.kbrepeat', cat: 'Performance', title: 'Teclado: delay curto e repetição rápida', evidence: 'documented', risk: 'low', group: 'keyboard',
    desc: 'KeyboardDelay=0 (250 ms) e KeyboardSpeed=31 (~30 car/s). Afeta somente repetição ao segurar tecla, não o tempo de resposta do primeiro toque.',
    changes: [R('HKCU', 'Control Panel\\Keyboard', 'KeyboardDelay', 'REG_SZ', '0'), R('HKCU', 'Control Panel\\Keyboard', 'KeyboardSpeed', 'REG_SZ', '31')],
    live: { kind: 'kb', args: [0, 31] }, liveUndo: { kind: 'kbPrev' } },
  // ---------------- BACKGROUND / PRIVACY / NOTIFICATIONS / UPDATES ----------------
  { id: 'bg.apps', cat: 'Background apps', title: 'Bloquear apps UWP em segundo plano (global)', evidence: 'documented', risk: 'low',
    desc: 'GlobalUserDisabled=1 impede apps da Store de rodarem em segundo plano.',
    changes: [R('HKCU', CV + '\\BackgroundAccessApplications', 'GlobalUserDisabled', 'REG_DWORD', 1)] },
  { id: 'ntf.tips', cat: 'Notifications', title: 'Desativar dicas, sugestões e conteúdo promovido', evidence: 'documented', risk: 'low',
    desc: 'Desliga ContentDeliveryManager (sugestões no Iniciar, dicas de tela de bloqueio, apps promovidos).',
    changes: [R('HKCU', CV + '\\ContentDeliveryManager', 'SubscribedContent-338389Enabled', 'REG_DWORD', 0), R('HKCU', CV + '\\ContentDeliveryManager', 'SystemPaneSuggestionsEnabled', 'REG_DWORD', 0), R('HKCU', CV + '\\ContentDeliveryManager', 'SoftLandingEnabled', 'REG_DWORD', 0)] },
  { id: 'priv.adid', cat: 'Privacy', title: 'Desativar ID de publicidade', evidence: 'documented', risk: 'low',
    desc: 'Impede apps de usarem seu ID de publicidade.', changes: [R('HKCU', CV + '\\AdvertisingInfo', 'Enabled', 'REG_DWORD', 0)] },
  { id: 'priv.telemetry', cat: 'Privacy', title: 'Telemetria no nível mínimo (política)', evidence: 'documented', risk: 'low', admin: true,
    desc: 'AllowTelemetry=0 só é respeitado em Enterprise/Education; em Home/Pro o Windows trata como 1 (Obrigatório). Não afeta atualizações nem o Defender.',
    changes: [R('HKLM', 'SOFTWARE\\Policies\\Microsoft\\Windows\\DataCollection', 'AllowTelemetry', 'REG_DWORD', 0)] },
  { id: 'upd.dopt', cat: 'Updates', title: 'Delivery Optimization sem P2P', evidence: 'documented', risk: 'low', admin: true,
    desc: 'DODownloadMode=0 impede o PC de enviar partes de atualizações a outros PCs (menos tráfego de upload em segundo plano). As atualizações continuam funcionando.',
    changes: [R('HKLM', 'SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\DeliveryOptimization\\Config', 'DODownloadMode', 'REG_DWORD', 0)] },
  { id: 'perf.visualfx', cat: 'Performance', title: 'Efeitos visuais: melhor desempenho + sem transparência', evidence: 'documented', risk: 'low',
    desc: 'VisualFXSetting=2 e transparência desativada. Libera um pouco de GPU/CPU no desktop.',
    changes: [R('HKCU', CV + '\\Explorer\\VisualEffects', 'VisualFXSetting', 'REG_DWORD', 2), R('HKCU', CV + '\\Themes\\Personalize', 'EnableTransparency', 'REG_DWORD', 0)] },
];
module.exports = { CATALOG };
